applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/icodebits/goit-devops.git
      path: django-chart
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/icodebits/goit-devops.git
    username: ${github_user}
    password: ${github_pat}

repoConfig:
  insecure: "true"
  enableLfs: "true"
